<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class ProductiveDeal extends Model
{
    protected $keyType = 'string';
    public $incrementing = false;
    public $timestamps = false; // Disable Laravel timestamps

    protected $fillable = [
        'id',
        'company_id',
        'project_id',
        'type',
        'name',
        'date',
        'end_date',
        'number',
        'deal_number',
        'suffix',
        'time_approval',
        'expense_approval',
        'client_access',
        'deal_type_id',
        'budget',
        'sales_status_updated_at',
        'tag_list',
        'original_deal_id',
        'profit_margin',
        'email_key',
        'purchase_order_number',
        'custom_fields',
        'position',
        'service_type_restricted_tracking',
        'tracking_type_id',
        'editor_config',
        'discount',
        'man_day_minutes',
        'rounding_interval_id',
        'rounding_method_id',
        'validate_expense_when_closing',
        'billable_time',
        'budget_warning',
        'estimated_time',
        'budgeted_time',
        'worked_time',
        'time_to_close',
        'probability',
        'previous_probability',
        'note_interpolated',
        'proposal_note_interpolated',
        'todo_count',
        'todo_due_date',
        'note',
        'proposal_note',
        'lost_comment',
        'closed_at',
        'delivered_on',
        'last_activity_at',
        'deleted_at',
        'sales_closed_at',
        'exchange_rate',
        'exchange_date',
        'sales_closed_on',
        'sample_data',
        'external_id',
        'external_sync',
        'manual_invoicing_status_id',
        'currency',
        'currency_default',
        'currency_normalized',
        'revenue',
        'revenue_default',
        'revenue_normalized',
        'services_revenue',
        'services_revenue_default',
        'services_revenue_normalized',
        'budget_total',
        'budget_total_default',
        'budget_total_normalized',
        'budget_used',
        'budget_used_default',
        'budget_used_normalized',
        'projected_revenue',
        'projected_revenue_default',
        'projected_revenue_normalized',
        'cost',
        'cost_default',
        'cost_normalized',
        'profit',
        'profit_default',
        'profit_normalized',
        'invoiced',
        'invoiced_default',
        'invoiced_normalized',
        'pending_invoicing',
        'pending_invoicing_default',
        'pending_invoicing_normalized',
        'manually_invoiced',
        'manually_invoiced_default',
        'manually_invoiced_normalized',
        'draft_invoiced',
        'draft_invoiced_default',
        'draft_invoiced_normalized',
        'amount_credited',
        'amount_credited_default',
        'amount_credited_normalized',
        'expense',
        'expense_default',
        'expense_normalized',
        'organization_type',
        'organization_id',
        'creator_meta_included',
        'company_meta_included',
        'document_type_meta_included',
        'proposal_document_type_meta_included',
        'responsible_meta_included',
        'deal_status_meta_included',
        'project_meta_included',
        'lost_reason_meta_included',
        'contract_meta_included',
        'contact_meta_included',
        'subsidiary_meta_included',
        'template_meta_included',
        'tax_rate_meta_included',
        'pipeline_meta_included',
        'origin_deal_meta_included',
        'approval_policy_assignment_meta_included',
        'custom_field_people_meta_included',
        'custom_field_attachments_meta_included',
    ];

    protected $casts = [
        'date' => 'date',
        'end_date' => 'date',
        'time_approval' => 'boolean',
        'expense_approval' => 'boolean',
        'client_access' => 'boolean',
        'budget' => 'decimal:2',
        'sales_status_updated_at' => 'datetime',
        'tag_list' => 'array',
        'profit_margin' => 'decimal:2',
        'custom_fields' => 'array',
        'position' => 'integer',
        'service_type_restricted_tracking' => 'boolean',
        'editor_config' => 'array',
        'discount' => 'decimal:2',
        'man_day_minutes' => 'integer',
        'validate_expense_when_closing' => 'boolean',
        'billable_time' => 'boolean',
        'budget_warning' => 'boolean',
        'estimated_time' => 'decimal:2',
        'budgeted_time' => 'decimal:2',
        'worked_time' => 'decimal:2',
        'time_to_close' => 'decimal:2',
        'probability' => 'decimal:2',
        'previous_probability' => 'decimal:2',
        'todo_count' => 'integer',
        'todo_due_date' => 'date',
        'closed_at' => 'datetime',
        'delivered_on' => 'date',
        'last_activity_at' => 'datetime',
        'deleted_at' => 'datetime',
        'sales_closed_at' => 'datetime',
        'exchange_date' => 'date',
        'sales_closed_on' => 'date',
        'sample_data' => 'boolean',
        'external_sync' => 'array',
        'exchange_rate' => 'decimal:6',
        'revenue' => 'decimal:2',
        'revenue_default' => 'decimal:2',
        'revenue_normalized' => 'decimal:2',
        'services_revenue' => 'decimal:2',
        'services_revenue_default' => 'decimal:2',
        'services_revenue_normalized' => 'decimal:2',
        'budget_total' => 'decimal:2',
        'budget_total_default' => 'decimal:2',
        'budget_total_normalized' => 'decimal:2',
        'budget_used' => 'decimal:2',
        'budget_used_default' => 'decimal:2',
        'budget_used_normalized' => 'decimal:2',
        'projected_revenue' => 'decimal:2',
        'projected_revenue_default' => 'decimal:2',
        'projected_revenue_normalized' => 'decimal:2',
        'cost' => 'decimal:2',
        'cost_default' => 'decimal:2',
        'cost_normalized' => 'decimal:2',
        'profit' => 'decimal:2',
        'profit_default' => 'decimal:2',
        'profit_normalized' => 'decimal:2',
        'invoiced' => 'decimal:2',
        'invoiced_default' => 'decimal:2',
        'invoiced_normalized' => 'decimal:2',
        'pending_invoicing' => 'decimal:2',
        'pending_invoicing_default' => 'decimal:2',
        'pending_invoicing_normalized' => 'decimal:2',
        'manually_invoiced' => 'decimal:2',
        'manually_invoiced_default' => 'decimal:2',
        'manually_invoiced_normalized' => 'decimal:2',
        'draft_invoiced' => 'decimal:2',
        'draft_invoiced_default' => 'decimal:2',
        'draft_invoiced_normalized' => 'decimal:2',
        'amount_credited' => 'decimal:2',
        'amount_credited_default' => 'decimal:2',
        'amount_credited_normalized' => 'decimal:2',
        'expense' => 'decimal:2',
        'expense_default' => 'decimal:2',
        'expense_normalized' => 'decimal:2',
        'creator_meta' => 'array',
        'company_meta' => 'array',
        'document_type_meta' => 'array',
        'proposal_document_type_meta' => 'array',
        'responsible_meta' => 'array',
        'deal_status_meta' => 'array',
        'project_meta' => 'array',
        'lost_reason_meta' => 'array',
        'contract_meta' => 'array',
        'contact_meta' => 'array',
        'subsidiary_meta' => 'array',
        'template_meta' => 'array',
        'tax_rate_meta' => 'array',
        'pipeline_meta' => 'array',
        'origin_deal_meta' => 'array',
        'approval_policy_assignment_meta' => 'array',
        'custom_field_people_meta' => 'array',
        'custom_field_attachments_meta' => 'array',
        'productive_created_at' => 'datetime',
        'productive_updated_at' => 'datetime',
    ];

    public function company(): BelongsTo
    {
        return $this->belongsTo(ProductiveCompany::class, 'company_id');
    }

    public function project(): BelongsTo
    {
        return $this->belongsTo(ProductiveProject::class, 'project_id');
    }

    public function originalDeal(): BelongsTo
    {
        return $this->belongsTo(self::class, 'original_deal_id');
    }
}
